apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: onepassworditems.onepassword.com
spec:
  group: onepassword.com
  versions:
    - name: v1
      storage: true
      served: true
      schema:
        openAPIV3Schema:
          type: object
          properties: 
            spec: 
              required: 
                - "itemPath"
              properties: 
                itemPath: 
                  type: "string"
              type: "object"
  names:
    kind: OnePasswordItem
    plural: onepassworditems
  scope: Namespaced
